import { StyleSheet } from "react-native";

export const lightTheme = {
    background: "#FFFFFF",
    text: "#000000",
    inactive: "#808080",
    section: "#F5F5F5",
    button: "#2196F3",
    buttonText: "#FFFFFF",
    buttonSelected: "#114b7a",
    music: "#E0E0E0",
    musicText: "#333333",
};

export const darkTheme = {
    background: "#161616",
    text: "#FFFFFF",
    inactive: "#8A8A8A",
    section: "#2D2D2D",
    button: "#0A2D49",
    buttonText: "#FFFFFF",
    buttonSelected: "#051725",
    music: "#333333",
    musicText: "#E0E0E0",
};

export const retroTheme = {
    background: "#BDB398",
    text: "#4242E7",
    inactive: "#807ABE",
    section: "#EBE3CD",
    button: "#C9B2A6",
    buttonText: "#FFFCF1",
    buttonSelected: "#655953",
    music: "#C9B2A6",
    musicText: "#FFFCF1",
};

export const createStyles = (theme) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background,
        paddingHorizontal: 16,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: theme.text,
        marginTop: 20,
    },
    subtitle: {
        fontsize: 16,
        color: '#888',
        marginTop: -8,
        marginBottom: 10,
        marginLeft: 1,
        fontWeight: '600',
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 20,
    },
    likeIcon: {
        fontSize: 35,
        marginTop: 15,
    },
    section: {
        marginBottom: 18,
        backgroundColor: theme.section,
        borderRadius: 10,
        padding: 14,
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 3,
        elevation: 1,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.text,
        marginBottom: 4,
    },
    sectionContent: {
        color: theme.text,
        fontSize: 15,
    },
    address: {
        color: theme.text,
        fontSize: 15,
        marginBottom: 2,
    },
    musicList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 4,
    },
    musicItem: {
        backgroundColor: theme.music,
        borderRadius: 12,
        paddingHorizontal: 10,
        paddingVertical: 4,
        marginRight: 8,
        marginBottom: 6,
        color: theme.musicText,
        fontSize: 13,
    },
    website: {
        color: '#2196F3',
        textDecorationLine: 'underline',
        fontSize: 15,
        marginTop: 2,
    },
    buttonRow: {
        flexDirection: 'row',
        gap: 10,
    },
    buttonRowButton: {
        flex: 1,
    },
    listItem: {
        backgroundColor: theme.section,
        padding: 16,
        borderRadius: 8,
        margin: 15,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    ListItemText: {
        color: theme.text,
        fontSize: 18,
    },
    openingHoursSection: {
        marginBottom: 18,
        backgroundColor: theme.section,
        borderRadius: 10,
        padding: 14,
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 3,
        elevation: 1,
    },
    openingHoursRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 4,
    },
    openingHoursDay: {
        color: theme.text,
        fontWeight: 'bold',
        fontSize: 15,
        width: 110,
    },
    openingHoursTime: {
        color: theme.text,
        fontSize: 15,
    },
    appButton: {
        backgroundColor: theme.button,
        paddingVertical: 14,
        borderRadius: 8,
        alignItems: 'center',
        marginBottom: 18,
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    appButtonText: {
        color: theme.buttonText,
        fontSize: 17,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    image: {
        marginBottom: 18,
        alignSelf: 'center',
        borderRadius: 10,
    },
    myLocation: {
        position: 'absolute',
        bottom: 32,
        right: 24,
        width: 56,
        height: 56,
        borderRadius: 28,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 6,
        borderWidth: 1,
        borderColor: '#ddd',
    },
    myLocationIcon: {
        width: 32,
        height: 32,
    },
});